---
  name: Install Httpd
  hosts: servers

  tasks:
    - name: Install Httpd on Red Hat/CentOS
      yum:                        # Package manager for Red Hat/CentOS
        name: httpd               # Specify the package name
        state: latest             # Ensure the latest version is installed
      when: ansible_os_family == "RedHat"  # Only run on Red Hat/CentOS

    - name: Install apache2 on Ubuntu
      apt:                        # Package manager for Debian/Ubuntu
        name: apache2             # Specify the package name
        state: latest             # Ensure the latest version is installed
      when: ansible_os_family == "Ubuntu"  # Only run on Ubuntu