-
  name: Install Nginx and Start It
  hosts: servers
  vars:
    - apps: [yum,httpd,telnet]  # List of applications to be installed
    - app: nginx  # Variable for the application name
  become: yes                     # Root User Privileges
  tasks:
    - name: Install Nginx
      apt:                        # Package manager for Debian/Ubuntu
        name: nginx               # Specify the package name
        state: latest             # Ensure the latest version is installed
      tags: i-nginx # Tag for Nginx installation

    - name: Ensure Nginx is running
      service:   
       name: "{{item}}" # Manage the service

     # name: "{{app}}"  # Use the variable for the application name
       state: started
       enabled: yes               # Ensure it starts on boot
      tags: ss-nginx # Tag for Nginx service management
      with_items: "{{ apps }}"  # Loop through the list of applications
      