---
- name: Password Management Playbook
  # This playbook manages user Passwords on remote servers.
  hosts: servers

  tasks:
    - name: Set user password
      user:
        name: paul  # Name of the user whose password will be set
        update_password: always  # Always update the password
        password: "{{'abcd123' | password_hash('sha512')}}"  # Password to be set, hashed using sha512
        